server:
  port: 8082

spring:
  data:
    mongodb:
      host: ${DATABASE_HOST}
      port: ${DATABASE_PORT}
      database: ${DATABASE_NAME}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}

feign:
  movie-forecast-parser:
    url: http://localhost:8000