server:
  port: 8991

bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}

geocoding:
  api-key: ${GEOCODING_API_KEY}

feign:
  movie-forecast-backend-user:
    url: http://localhost:8990
  movie-forecast-backend-storage:
    url: http://localhost:8993