server:
  port: 8992

feign:
  movie-forecast-parser:
    url: http://localhost:8999
  movie-forecast-backend-user:
    url: http://localhost:8990
  movie-forecast-backend-storage:
    url: http://localhost:8993
  movie-forecast-bot:
    url: http://localhost:8991