server:
  port: 8081

bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}

geocoding:
  api-key: ${GEOCODING_API_KEY}

feign:
  movie-forecast-parser:
    url: http://localhost:8000
  movie-forecast-backend:
    url: http://localhost:8080